### PR TITLE
Added small pagination property access bug fix

### PR DESCRIPTION
**Pull request by penwoodjon**

### CODE REVIEW

**Review by sarus — CHANGES_REQUESTED** [review]
@penwoodjon I'm getting hits on a hash with no summary tags:

image


Hash is: 830e45cddc3c096c7a0125c1e5717071f2ec6251

**Comment by sarus** [comment]
Unrelated to the hash.  Do you know if we'd expect IP address lookups to have hits for endpoints?

I see this IP in the web interface: 
Console Visible IP Address: 173.50.120[.]113

Located here: https://usea1-partners.sentinelone.net/incidents/threats/1225467789945845043/overview

But don't get a hit.

**Comment by sarus** [comment]
@penwoodjon Also just noticed this but in the:

```
.concat(malicousThreatsCount ? `Malicous Threats: ${malicousThreatsCount}` : [])
```

Typo here `Malicous` -> `Malicious`

**Comment by penwoodjon** [comment]
> m getting hits on a hash with no summary tags:

Added a few more summary tags and solved a bug in here

**Comment by penwoodjon** [comment]
> Unrelated to the hash. Do you know if we'd expect IP address lookups to have hits for endpoints?
> 
> I see this IP in the web interface: Console Visible IP Address: 173.50.120[.]113
> 
> Located here: https://usea1-partners.sentinelone.net/incidents/threats/1225467789945845043/overview
> 
> But don't get a hit.

This is due to the endpoint no longer being online.  I added an addition request though to ask for decommissioned endpoints so you should be getting results now.

**Comment by penwoodjon** [comment]
> @penwoodjon Also just noticed this but in the `createSummary` method:
> 
> ```
> .concat(malicousThreatsCount ? `Malicous Threats: ${malicousThreatsCount}` : [])
> ```
> 
> Typo here `Malicous` -> `Malicious`

Thanks! Fixed and pushed!

**Review by sarus — APPROVED** [review]
@penwoodjon Looks great!

**Pull request merged**
